//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Кулинарная_книга
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int ID_recipe { get; set; }
        public string Name { get; set; }
        public byte[] ImagePreview { get; set; }
        public string Type { get; set; }
        public string Ingridients { get; set; }
        public Nullable<int> ID_user { get; set; }
    
        public virtual User User { get; set; }
    }
}
